name: Deploy Quartz Site
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npx quartz build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          ssh_key: ${{ b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCUrfqVCOW6/bl6bKgWjv0DnVaOQF5/Za+PFC8Ds40u8gAAAKDgyy0v4Mst
LwAAAAtzc2gtZWQyNTUxOQAAACCUrfqVCOW6/bl6bKgWjv0DnVaOQF5/Za+PFC8Ds40u8g
AAAEAVPFfqFEWd7k0U3MIzQDDHGES7C+2x0V4iM9hzINFMeJSt+pUI5br9uXpsqBaO/QOd
Vo5AXn9lr48ULwOzjS7yAAAAGG1oYWZhbjQyMjIwMDg5QGdtYWlsLmNvbQECAwQF }}
          remote_branch: gh-pages
          publish_dir: ./public
          force_orphan: true


